name: k3vo-platform-client
repository: https://github.com/kevinomyonga/k3vo-platform-client

sdkPath: .fvm/flutter_sdk # Points to FVM-managed Flutter SDK

packages:
  - apps/**
  - packages/**

scripts:
  ###############################################
  ##              APP COMMANDS                 ##
  ###############################################
  gen-app-icon:
    run: fvm flutter pub run flutter_launcher_icons
    description: Generates App resource app icon.
    exec:
      failFast: true
    packageFilters:
      dirExists:
        - android
        - ios

  gen-app-splash:
    run: fvm flutter pub run flutter_native_splash:create --flavors development,staging,production
    description: Generates App resource splash screen.
    exec:
      failFast: true
    packageFilters:
      dirExists:
        - android
        - ios

  ###############################################
  ##             CODEGEN COMMANDS              ##
  ###############################################
  codegen:pub-get:
    description: Install all dependencies.
    run: flutter pub get
    exec:
      failFast: true
    packageFilters:
      dirExists:
        - lib

  codegen:pub-upgrade:
    description: Upgrade all dependencies.
    run: flutter pub upgrade
    exec:
      failFast: true
    packageFilters:
      dirExists:
        - lib

  codegen:build_runner:
    description: Generate code for all packages using build_runner
    # We have to delete all generated by flutter_gen code prior generation because it doesn't
    # support incremental generation, nor it supports deleting files that are not needed anymore
    run: 'find . -type f -name "*.gen.dart" -delete && flutter packages pub run build_runner build --delete-conflicting-outputs'
    exec:
      # concurrency set to ONE because we SHOULD generate all code for packages prior we
      # started generation for the app
      concurrency: 1
      failFast: true
    packageFilters:
      dependsOn: "build_runner"
      ignore: "dependencies"

  ###############################################
  ##             QUALITY COMMANDS              ##
  ###############################################
  quality:analyze:
    description: Run `dart analyze` in selected or all packages. Includes prompt for packages.
    exec: dart analyze --fatal-infos .
    packageFilters:
      dirExists:
        - lib

  quality:check-format:
    description: Check the format of a specific package in this project.
    run: dart format --set-exit-if-changed .
    exec:
      failFast: true

  quality:clean:
    description: Clean Flutter package and install dependencies
    exec: flutter clean && flutter pub get
    packageFilters:
      dirExists:
        - lib

  quality:check-all:
    description: Prepare to commit by checking all things
    run: melos quality:check-format && melos quality:analyze && melos test
    exec:
      failFast: true

  quality:fix:
    description: Apply automated fixes to Dart source code of a specific package in this project.
    run: dart fix --apply
    exec:
      failFast: true
    packageFilters:
      dirExists:
        - lib
