// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmCsqPXkSq6L7MhWRxCg3ln3E80htK1II',
    appId: '1:644507664170:web:700fe8b33c7204fcbf2853',
    messagingSenderId: '644507664170',
    projectId: 'k3vo-platform',
    authDomain: 'k3vo-platform.firebaseapp.com',
    storageBucket: 'k3vo-platform.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZE1tBZl21LEWVGGzVhNDRscSOBOC6SnY',
    appId: '1:644507664170:android:98f5b18c6ed0696bbf2853',
    messagingSenderId: '644507664170',
    projectId: 'k3vo-platform',
    storageBucket: 'k3vo-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBvx3L4Vqprjf17mkrwiayVsLSLJPhDL4',
    appId: '1:644507664170:ios:7c8c195d9891b88dbf2853',
    messagingSenderId: '644507664170',
    projectId: 'k3vo-platform',
    storageBucket: 'k3vo-platform.firebasestorage.app',
    iosClientId: '644507664170-19fs0qplsc0o9cn382ktdvjt5uv46s7t.apps.googleusercontent.com',
    iosBundleId: 'ke.me.k3vo.app.dev',
  );
}
