name: k3vo_foundation
description: A Flutter package that contains foundational utilities, constants, and helpers for the K3VO platform client app.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  firebase_core: ^3.15.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  package_info_plus: ^8.3.0
  share_plus: ^11.0.0
  url_launcher: ^6.3.1

  k3vo_data: ^2025.7.0
  k3vo_localization: ^2025.7.0
  k3vo_router: ^2025.7.0
  collection: ^1.19.1
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
