name: k3vo_ui_kit
description: UI components and utilities for the K3VO platform client app
version: 2025.7.0+1
homepage: https://github.com/kevinomyonga/k3vo-platform-client/tree/main/packages/design/k3vo_ui_kit
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  adaptive_chameleon_theme: ^2025.7.0
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  split_screen: ^1.0.5
  video_player: ^2.10.0

  k3vo_foundation: ^2025.7.0
  k3vo_localization: ^2025.7.0

dev_dependencies:
  build_runner: any
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/branding/
    - assets/images/icons/
    - assets/images/icons/language/
    - assets/images/icons/launcher/
    - assets/videos/

flutter_gen:
  assets:
    enabled: true
    outputs:
      # Set to true if you want this package to be a package dependency
      # See: https://flutter.dev/docs/development/ui/assets-and-images#from-packages
      package_parameter_enabled: true

  output: lib/src/generated/
  line_length: 80

  integrations:
    flutter_svg: true
    rive: true
